config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'shelf#index', via: :all
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :orders
    resources :line_items, only: :create
    resources :carts, only: [:show, :destroy]
  end

  resources :products do
    get :who_bought, on: :member
    patch :toggle_shelf, on: :member
  end

  resources :users_admin, except: :update, controller: 'users' do
    get 'profile', on: :member
  end
end

app/views/shared/_flash_messages.html.haml
.container
  .row
    .col-md-12
      #flash-messages
        - flash.each do |key, message|
          %div{:class => "text-center alert alert-#{key == 'notice' ? 'success' : 'danger'}"}
            = message

app/views/shared/_header.html.haml
%body
  %header{:role => "banner"}
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "DS Store Online", root_path, class: "navbar-brand"
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-left
            %li= link_to t('.home'), root_path
            %li
              %a{:href => "#"}= t('.questions')
            %li
              %a{:href => "#"}= t('.news')
            %li
              %a{:href => "#"}= t('.contact')
          = form_tag root_path, :method => 'get', id: 'search-form', class: "navbar-form navbar-left" do
            %p
              = text_field_tag :search, params[:search], class: "form-control", placeholder: t('.search.input')
              = submit_tag t(".search.button"), class: "btn btn-default", :name => nil
          %ul.nav.navbar-nav.navbar-right
            .locale
              = "#{t('.language')}:"
              \#{link_to_unless_current t('.english'), locale: 'en'} |
              \#{link_to_unless_current t('.polish'), locale: 'pl'}
            - if user_signed_in?
              %p.navbar-text
                = t('.signed_in_as')
                = (current_user.name == "" || current_user.name.nil?) ? current_user.email : current_user.name
            - else
              %li= link_to t('.sign_up'), new_user_registration_path
              %li= link_to t('.sign_in'), new_user_session_path
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = t('.administration')
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to t('.panel'), profile_users_admin_path(current_user.id)
                  - if current_user.admin?
                    %li.divider{:role => "separator"}
                    %li= link_to t('.orders'), orders_path
                    %li= link_to t(".products"), products_path
                    %li= link_to t(".users"), users_admin_index_path
                    %li.divider{:role => "separator"}
                  %li= link_to t('.sign_out'), destroy_user_session_path, method: :delete

app/views/shared/_main.html.haml
= yield