config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'shelf#index', via: :all
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :orders
    resources :line_items, only: :create
    resources :carts, only: [:show, :destroy]
  end

  resources :products do
    get :who_bought, on: :member
    patch :toggle_shelf, on: :member
  end

  resources :users_admin, except: :update, controller: 'users' do
    get 'profile', on: :member
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product: product)
    end
    current_item
  end

  def price_calculation
    line_items.to_a.sum { |item| item.price_calculation }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :destroy]

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id = session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Koszyk jest pusty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

  protected

  def resource_not_found
    logger.error "Attempt to access invalid cart #{params[:id]}"
    message = "The cart you are looking for could not be found"
    flash[:alert] = message
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
%h2 DS Store Cart
%table.table.table-striped
  = render cart.line_items
  %tr
    %td.text-right{:colspan => "2"}
      %b Total Price:
    %td
      %b= number_to_currency(cart.price_calculation)
.actions
  = link_to "Checkout", new_order_path, class: "btn btn-success"
  = button_to 'Empty Cart', cart_path(@cart), method: :delete, |
    data: { confirm: t(:are_you_sure), title: t('confirm_delete'), commit: t(:delete), cancel: t(:cancel) },                       |
    class: "btn btn-danger"                                    |
  = link_to 'Back to Shelf', root_path, class: "btn btn-default"

app/views/carts/show.html.haml
= render @cart