config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'shelf#index', via: :all
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :orders
    resources :line_items, only: :create
    resources :carts, only: [:show, :destroy]
  end

  resources :products do
    get :who_bought, on: :member
    patch :toggle_shelf, on: :member
  end

  resources :users_admin, except: :update, controller: 'users' do
    get 'profile', on: :member
  end
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :line_item_do_not_exist?

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :title, :description, :price

  belongs_to :user
  has_many :line_items
  has_many :orders, through: :line_items

  translates :title, :description

  def self.search(search)
    if search
      where("title LIKE ? AND shelf = ?", "%#{search}%", true).order(:title)
    else
      where(shelf: true).order(:title)
    end
  end

  private

  def line_item_do_not_exist?
    unless line_items.empty?
      errors.add('base', 'Przedmiot jest w koszyku!')
      throw :abort
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :toggle_shelf]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      flash[:success] = "Product has been created by #{current_user.email}"
      redirect_to products_path
    else
      flash.now[:danger] = "Product has not been created"
      render :new
    end
  end

  def show
  end

  def edit
    unless @product.user == current_user || current_user.admin?
      flash[:alert] = "You can only edit your own product."
      redirect_to root_path
    end
  end

  def update
    unless @product.user == current_user
      flash[:danger] = "You can only edit your own product."
      redirect_to root_path
    else
      if @product.update(product_params)
        flash[:notice] = "Product has been updated"
        redirect_to @product
      else
        flash.now[:danger] = "Product has not been updated"
        render :edit
      end
    end
  end

  def destroy
    unless @product.user == current_user
      flash[:alert] = "You can only delete your own products."
      redirect_to root_path
    else
      if @product.destroy
        flash[:success] = "Product has been deleted"
        redirect_to products_path
      end
    end
  end

  # def who_bought
  #   @product = Product.find(params[:id])
  #   @latest_order = @product.orders.order(:updated_at).last
  #
  #   if stale?(@latest_order)
  #     respond_to do |format|
  #       format.atom
  #       format.json { render json: @product.to_json(include: :orders) }
  #     end
  #   end
  # end

  def toggle_shelf
    @product.toggle(:shelf)
    if @product.save
      redirect_to products_path
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end

  protected

  def resource_not_found
    message = "The product you are looking for could not be found"
    flash[:alert] = message
    redirect_to root_path
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.row
  .col-md-12
    - if @product.errors.any?
      .panel.panel-danger.col-md-offset-1
        .panel-heading
          %h2.panel-title
            = pluralize(@product.errors.count, "error")
            prohibited this article from being saved:
          .panel-body
            %ul
              - @product.errors.full_messages.each do |msg|
                %li
                  = msg
    = form_for @product, html: {class: "form-horizontal", role: "form", multipart: true} do |f|
      .form-group
        .col-md-1.control-label
          = f.label :title
        .col-md-11
          = f.text_field :title, class: "form-control", placeholder: "Title of Product", autofocus: true
      .form-group
        .col-md-1.control-label
          = f.label :image
        .col-md-11
          = f.file_field :image
      .form-group
        .col-md-1.control-label
          = f.label :description
        .col-md-11
          = f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of Product"
      .form-group
        .col-md-1.control-label
          = f.label :price
        .col-md-11
          = f.text_field :price, col: 5, class: "form-control", placeholder: "Price of Product"
      .form-group
        .col-md-offset-1.col-md-11
          = f.submit class: "btn btn-primary btn-lg pull-right"

app/views/products/edit.html.haml
%h3.text-center Edit a Product
= render "form"

app/views/products/index.html.haml
- if user_signed_in?
  = link_to t('.new'), new_product_path, class: "btn btn-default btn-lg"
- if @products.empty?
  %h1#no-products No Products Created
- else
  %table.table.table-hover
    %tr
      %th= Product.human_attribute_name(:title)
      %th= Product.human_attribute_name(:image)
      %th= Product.human_attribute_name(:description)
      %th= Product.human_attribute_name(:price)
      %th= Product.human_attribute_name(:author)
      %th= Product.human_attribute_name(:shelf)
    - @products.each do |product|
      %tr
        %td.product-title
          %h3= link_to product.title, product_path(product)
        %td.product-image= image_tag product.image.url(:thumb), class: "img-thumbnail"
        %td.product-description= sanitize(product.description.truncate(350, separator: " "))
        %td.product-price
          %strong= product.price
        %td
          %small
            = "#{t('.created_by')}: #{product.user.email}"
        %td.product-toggle= button_to "#{product.shelf? ? t(".hide") : t('.show')}", toggle_shelf_product_path(product), class: "btn btn-warning", method: :patch

app/views/products/new.html.haml
%h3.text-center Adding New Product
= render "form"

app/views/products/show.html.haml
%h1= @product.title
= image_tag @product.image.url(:medium), class: "img-thumbnail"
.glyphicon.glyphicon-calendar
  = @product.created_at.strftime("%b %d %Y")
%div
  = sanitize @product.description
%strong= @product.price
- if current_user == @product.user && user_signed_in? || current_user.admin?
  .product-actions
    = link_to "Edit Product", edit_product_path(@product), class: "btn btn-primary btn-lg btn-space"
    = link_to "Delete Product", product_path(@product), method: :delete, |
      data: {confirm: "Are you sure you want to delete product?"},       |
      class: "btn btn-danger btn-lg btn-space"                           |
= link_to "Who bought", who_bought_product_url(@product.id, format: :atom)