config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'shelf#index', via: :all
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :orders
    resources :line_items, only: :create
    resources :carts, only: [:show, :destroy]
  end

  resources :products do
    get :who_bought, on: :member
    patch :toggle_shelf, on: :member
  end

  resources :users_admin, except: :update, controller: 'users' do
    get 'profile', on: :member
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cart
  belongs_to :order, optional: true

  validates_presence_of :product_id

  def price_calculation
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: :create
  skip_before_action :authenticate_user!, only: :create

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html {redirect_to @line_item.cart, notice: 'Line item was successfully created.'}
        format.json {render :show, status: :created, location: @line_item}
      else
        format.html {redirect_to @line_item.cart, flash: {danger: 'Line item wasn\'t created.'}}
      end
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for(line_item) do |f|
  - if line_item.errors.any?
    #error_explanation
      %h2
        = pluralize(line_item.errors.count, "error")
        prohibited this line_item from being saved:
      %ul
        - line_item.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :product_id
    = f.text_field :product_id
  .field
    = f.label :cart_id
    = f.text_field :cart_id
  .actions
    = f.submit

app/views/line_items/_line_item.html.haml
%tr
  %td
    = line_item.quantity
    ×
  %td= line_item.product.title
  %td= number_to_currency(line_item.price_calculation)

app/views/line_items/_line_item.text.haml
= sprintf("%2d x %s", line_item.quantity, truncate(line_item.product.title, length: 50))

app/views/line_items/edit.html.haml
%h1 Editing Line Item
= render 'form', line_item: @line_item
= link_to 'Show', @line_item
|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%p#notice= notice
%h1 Line Items
%table
  %thead
    %tr
      %th Product
      %th Cart
      %th{:colspan => "3"}
  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product
        %td= line_item.cart
        %td= link_to 'Show', line_item
        %td= link_to 'Edit', edit_line_item_path(line_item)
        %td= link_to 'Destroy', line_item, method: :delete, data: { confirm: t(:are_you_sure) }
%br/
= link_to 'New Line Item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New Line Item
= render 'form', line_item: @line_item
= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice
%p
  %strong Product:
  = @line_item.product
%p
  %strong Cart:
  = @line_item.cart
= link_to 'Edit', edit_line_item_path(@line_item)
|
= link_to 'Back', line_items_path